Create database OMS;
CREATE TABLE order_header (
    order_id VARCHAR(40) PRIMARY KEY,
    order_type_id VARCHAR(40),
    order_name VARCHAR(100),
    external_id VARCHAR(100),
    sales_channel_enum_id VARCHAR(40),
    order_date DATETIME,
    priority VARCHAR(20),
    entry_date DATETIME,
    pick_sheet_printed_date DATETIME,
    visit_id VARCHAR(40),
    status_id VARCHAR(40),
    created_by VARCHAR(40),
    first_attempt_order_id VARCHAR(40),
    currency_uom VARCHAR(10),
    sync_status_id VARCHAR(40),
    billing_account_id VARCHAR(40),
    origin_facility_id VARCHAR(40),
    web_site_id VARCHAR(40),
    product_store_id VARCHAR(40),
    terminal_id VARCHAR(40),
    transaction_id VARCHAR(40),
    auto_order_shopping_list_id VARCHAR(40),
    needs_inventory_issuance BOOLEAN DEFAULT FALSE,
    is_rush_order BOOLEAN DEFAULT FALSE,
    internal_code VARCHAR(40),
    remaining_sub_total DECIMAL(12, 2),
    grand_total DECIMAL(12, 2),
    is_viewed BOOLEAN DEFAULT FALSE,
    invoice_per_shipment BOOLEAN DEFAULT FALSE,
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    expire_date DATE,
    locale_string VARCHAR(20),
    customer_classification_id VARCHAR(40),
    presentment_currency_uom VARCHAR(10),
    auto_approve BOOLEAN DEFAULT FALSE,
    status_flow_id VARCHAR(40)
);


CREATE TABLE order_item (
    order_id VARCHAR(40),                         
    order_item_seq_id VARCHAR(20),              
    external_id VARCHAR(100),
    order_item_type_id VARCHAR(40),
    order_item_group_seq_id VARCHAR(20),
    is_item_group_primary BOOLEAN DEFAULT FALSE,
    from_inventory_item_id VARCHAR(40),
    budget_id VARCHAR(40),
    budget_item_seq_id VARCHAR(20),
    product_id VARCHAR(40),
    supplier_product_id VARCHAR(40),
    product_feature_id VARCHAR(40),
    prod_catalog_id VARCHAR(40),
    product_category_id VARCHAR(40),
    is_promo BOOLEAN DEFAULT FALSE,
    quote_id VARCHAR(40),
    quote_item_seq_id VARCHAR(20),
    shopping_list_id VARCHAR(40),
    shopping_list_item_seq_id VARCHAR(20),
    subscription_id VARCHAR(40),
    deployment_id VARCHAR(40),
    quantity DECIMAL(10, 2),
    cancel_quantity DECIMAL(10, 2),
    selected_amount DECIMAL(10, 2),
    unit_price DECIMAL(10, 2),
    unit_list_price DECIMAL(10, 2),
    unit_average_cost DECIMAL(10, 2),
    unit_recurring_price DECIMAL(10, 2),
    is_modified_price BOOLEAN DEFAULT FALSE,
    recurring_freq_uom_id VARCHAR(20),
    item_description TEXT,
    comments TEXT,
    corresponding_po_id VARCHAR(40),
    status_id VARCHAR(40),
    sync_status_id VARCHAR(40),
    estimated_ship_date DATE,
    auto_cancel_date DATE,
    dont_cancel_set_date DATE,
    dont_cancel_set_user_login VARCHAR(40),
    ship_before_date DATE,
    ship_after_date DATE,
    cancel_back_order_date DATE,
    override_gl_account_id VARCHAR(40),
    sales_opportunity_id VARCHAR(40),
    change_by_user_login_id VARCHAR(40),
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    ship_group_seq_id VARCHAR(20),
    return_till_date DATE,
    promised_datetime DATETIME,
    shipment_id VARCHAR(40),
    is_new_product BOOLEAN DEFAULT FALSE,
    available_to_promise DECIMAL(10, 2),
    estimated_delivery_date DATE,
    requested_delivery_date DATE,
    requested_delivery_time TIME,
    requested_ship_meth_type_id VARCHAR(40),
    delivery_window VARCHAR(40),
    tax_code VARCHAR(20),

    PRIMARY KEY (order_id, order_item_seq_id),
    FOREIGN KEY (order_id) REFERENCES order_header(order_id)
);


CREATE TABLE order_status (
    order_status_id VARCHAR(40) PRIMARY KEY,            
    status_id VARCHAR(40),                                
    order_id VARCHAR(40),                                
    order_item_seq_id VARCHAR(20),                        
    order_payment_preference_id VARCHAR(40),             
    status_datetime DATETIME,                             
    status_user_login VARCHAR(40),                        
    change_reason TEXT,                                 
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    change_reason_enum_id VARCHAR(40)                   
);


CREATE TABLE order_adjustment (
    order_adjustment_id VARCHAR(40) PRIMARY KEY,
    order_adjustment_type_id VARCHAR(40),
    order_id VARCHAR(40),
    order_item_seq_id VARCHAR(20),
    ship_group_seq_id VARCHAR(20),
    comments TEXT,
    description TEXT,
    amount DECIMAL(12, 2),
    recurring_amount DECIMAL(12, 2),
    amount_already_included BOOLEAN DEFAULT FALSE,
    product_promo_id VARCHAR(40),
    product_promo_rule_id VARCHAR(40),
    product_promo_action_seq_id VARCHAR(20),
    product_feature_id VARCHAR(40),
    corresponding_product_id VARCHAR(40),
    tax_authority_rate_seq_id VARCHAR(40),
    source_reference_id VARCHAR(40),
    source_percentage DECIMAL(6, 3),
    customer_reference_id VARCHAR(40),
    primary_geo_id VARCHAR(40),
    secondary_geo_id VARCHAR(40),
    exempt_amount DECIMAL(12, 2),
    tax_auth_geo_id VARCHAR(40),
    tax_auth_party_id VARCHAR(40),
    override_gl_account_id VARCHAR(40),
    include_in_tax BOOLEAN DEFAULT FALSE,
    include_in_shipping BOOLEAN DEFAULT FALSE,
    is_manual BOOLEAN DEFAULT FALSE,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_by_user_login VARCHAR(40),
    last_modified_date DATETIME,
    last_modified_by_user_login VARCHAR(40),
    original_adjustment_id VARCHAR(40),
    old_amount_per_quantity DECIMAL(12, 2),
    old_percentage DECIMAL(6, 3),
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    billing_shipment_id VARCHAR(40)
);

CREATE TABLE order_contact_mech (
    order_id VARCHAR(40),
    contact_mech_purpose_type_id VARCHAR(40),
    contact_mech_id VARCHAR(40),
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id, contact_mech_purpose_type_id, contact_mech_id)
);


CREATE TABLE order_item_contact_mech (
    order_id VARCHAR(40),
    order_item_seq_id VARCHAR(20),
    contact_mech_purpose_type_id VARCHAR(40),
    contact_mech_id VARCHAR(40),
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id, order_item_seq_id, contact_mech_purpose_type_id, contact_mech_id)
);


CREATE TABLE order_item_shipping_group (
    order_id VARCHAR(40),
    ship_group_seq_id VARCHAR(20),
    shipment_method_type_id VARCHAR(40),
    supplier_party_id VARCHAR(40),
    vendor_party_id VARCHAR(40),
    carrier_party_id VARCHAR(40),
    carrier_role_type_id VARCHAR(40),
    facility_id VARCHAR(40),
    contact_mech_id VARCHAR(40),
    telecom_contact_mech_id VARCHAR(40),
    tracking_number VARCHAR(100),
    shipping_instructions TEXT,
    may_split BOOLEAN DEFAULT FALSE,
    gift_message TEXT,
    is_gift BOOLEAN DEFAULT FALSE,
    ship_after_date DATE,
    ship_by_date DATE,
    estimated_ship_date DATE,
    estimated_delivery_date DATE,
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    carrier_account_number VARCHAR(100),
    carrier_service VARCHAR(100),
    order_facility_id VARCHAR(40),
    PRIMARY KEY (order_id, ship_group_seq_id)
);


CREATE TABLE order_payment_preference (
    order_payment_preference_id VARCHAR(40) PRIMARY KEY,
    order_id VARCHAR(40),
    order_item_seq_id VARCHAR(20),
    ship_group_seq_id VARCHAR(20),
    product_price_purpose_id VARCHAR(40),
    payment_method_type_id VARCHAR(40),
    payment_method_id VARCHAR(40),
    fin_account_id VARCHAR(40),
    security_code VARCHAR(20),
    track2 TEXT,
    present_flag BOOLEAN DEFAULT FALSE,
    swiped_flag BOOLEAN DEFAULT FALSE,
    overflow_flag BOOLEAN DEFAULT FALSE,
    max_amount DECIMAL(12, 2),
    process_attempt INT,
    billing_postal_code VARCHAR(20),
    manual_auth_code VARCHAR(40),
    manual_ref_num VARCHAR(40),
    status_id VARCHAR(40),
    needs_nsf_retry BOOLEAN DEFAULT FALSE,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_by_user_login VARCHAR(40),
    last_modified_date DATETIME,
    last_modified_by_user_login VARCHAR(40),
    last_updated_stamp DATETIME,
    last_updated_tx_stamp DATETIME,
    created_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_tx_stamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    payment_mode VARCHAR(40),
    card_name VARCHAR(100),
    presentment_amount DECIMAL(12, 2),
    presentment_currency_uom VARCHAR(10),
    exchange_rate DECIMAL(12, 6),
    request_id VARCHAR(40),
    parent_ref_num VARCHAR(40),
    application_identifier VARCHAR(40)
);

create database shopify_order_mapping;
use shopify_order_mapping;
show tables;